# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"

  # Disable the local share so there is no weird leakage between the
  # test project path & things that may in the current directory
  config.vm.synced_folder ".", "/vagrant", disabled: true

  if ENV.key? "WORKSTATION_PROJECT_PATH"
    config.vm.synced_folder ENV.fetch("WORKSTATION_PROJECT_PATH"), "/projects"
  end
end
