VAGRANT:=tmp/vagrant

WORKSTATION_VAGRANTFILE=$(CURDIR)/test/Vagrantfile
WORKSTATION_HOME:=$(CURDIR)/tmp/data
WORKSTATION_PROJECT_PATH:=$(CURDIR)/tmp/scratch

ENV=env \
		PATH=$(CURDIR)/bin:$$PATH \
		WORKSTATION_HOME=$(WORKSTATION_HOME) \
		WORKSTATION_VAGRANTFILE=$(WORKSTATION_VAGRANTFILE)

$(WORKSTATION_PROJECT_PATH):
	mkdir -p $@

$(VAGRANT): $(WORKSTATION_PROJECT_PATH)
	$(ENV) workstation up $<
	mkdir -p $(@D)
	touch $@

.PHONY: test
test: $(VAGRANT)
	$(ENV) WORKSTATION_PROJECT_PATH=$(WORKSTATION_PROJECT_PATH) bats test/*_test.bats

.PHONY: clean
clean: 
	-env VAGRANT_CWD=$(dir $(WORKSTATION_VAGRANTFILE)) vagrant destroy -f 2>&1
	rm -rf $(VAGRANT) $(WORKSTATION_HOME) $(WORKSTATION_PROJECT_PATH)
